package me.ppgome.critterGuard;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.minimessage.MiniMessage;
import org.bukkit.configuration.InvalidConfigurationException;
import org.bukkit.configuration.file.FileConfiguration;

/**
 * This class interacts directly with the config.yml file generated by the plugin.
 *
 * The config handles the custom prefix, messages, and some toggleable options.
 */
public class CGConfig {
    /**
     * The instance of the plugin.
     */
    private CritterGuard plugin;
    /**
     * The instance of the MiniMessage API.
     */
    private MiniMessage mm;

    // Others
    public String PREFIX;

    // Toggles
    public boolean CAN_BREED_LOCKED_ANIMALS;
    public boolean LOG_MOUNT_NOTIFICATIONS;
    public boolean LOG_DISMOUNT_NOTIFICATIONS;
    public boolean LOG_DEATH_NOTIFICATIONS;
    public boolean ENABLE_DISGUISE_SADDLES;
    public boolean ENABLE_MINIMAP_MOD_OUTPUT;

    // Messages
    /*
    Note: Values that support placeholders (playernames, buttons, other Strings) should be saved as String.
        Otherwise, store them as Component and deserialize them through MiniMessage right away.

    Placeholders need to be replaced at request and cannot be set here. Use the methods in MessageUtils to deserialize.
     */
    public String GRANTED_FULL_ACCESS;
    public String GRANTED_PASSENGER_ACCESS;
    public String TARGET_GRANTED_FULL_ACCESS;
    public String TARGET_GRANTED_PASSENGER_ACCESS;
    public String REVOKED_FULL_ACCESS;
    public String REVOKED_PASSENGER_ACCESS;
    public String TARGET_REVOKED_FULL_ACCESS;
    public String TARGET_REVOKED_PASSENGER_ACCESS;
    public String ACCESS_NO_PLAYER;
    public Component ALREADY_HAS_ACCESS;
    public Component ALREADY_HAS_NO_ACCESS;
    public Component DOES_NOT_SUPPORT_PASSENGERS;
    public String DISGUISE_SUCCESS;
    public Component DISGUISE_VIEW_SELF_ENABLED;
    public Component DISGUISE_VIEW_SELF_DISABLED;
    public Component DISGUISE_ALREADY_ENABLED;
    public Component DISGUISE_ALREADY_DISABLED;
    public String GPS_NO_MATCH;
    public Component GPS_NO_PLAYERMETA;
    public Component LIST_DOES_NOT_EXIST_OR_OWN;
    public Component LIST_NO_MATCH;
    public String NOTIFICATION_MOUNTED;
    public String NOTIFICATION_DISMOUNTED;
    public String NOTIFICATION_DIED;
    public Component NOTIFICATION_TOGGLE_ON;
    public Component NOTIFICATION_TOGGLE_OFF;
    public Component NOTIFICATION_ALREADY_ON;
    public Component NOTIFICATION_ALREADY_OFF;
    public Component PERMISSION_COMMAND;
    public String PERMISSION_INTERACT;
    public String PERMISSION_MOUNT;
    public String SEAT_SWAP_SUCCESS;
    public Component SEAT_SWAP_FAILURE;
    public Component TAMING_TO_THEMSELVES;
    public String TAMING_TO_OTHERS;
    public Component UNTAME;
    public Component NOT_TAMED;
    public Component TAMED_NOT_YOURS;
    public String TELEPORT_TO;
    public String TELEPORT_HERE;
    public String TELEPORT_NO_PLAYER;
    public Component TELEPORT_NO_PLAYERMETA;
    public String  TELEPORT_NO_MATCH;
    public String CLICK_GRANT_FULL_ACCESS;
    public String CLICK_GRANT_PASSENGER_ACCESS;
    public String CLICK_REVOKE_FULL_ACCESS;
    public String CLICK_REVOKE_PASSENGER_ACCESS;
    public String CLICK_TAME;
    public String CLICK_UNTAME;
    public String CLICK_INFO;
    public Component CLICK_TIMEOUT;

    //------------------------------------------------------------------------------------------------------------------

    /**
     * Initializes the configuration class and creates/reloads the config.yml file.
     *
     * @param plugin The instance of the plugin
     */
    public CGConfig(CritterGuard plugin) {
        this.plugin = plugin;
        mm = MiniMessage.miniMessage();
        plugin.saveDefaultConfig();
        plugin.reloadConfig();
        reload();
    }

    //------------------------------------------------------------------------------------------------------------------

    /**
     * Reloads the configuration and fetches the latest data from the config.yml file.
     */
    public void reload() {
        plugin.reloadConfig();
        FileConfiguration config = plugin.getConfig();
        String errorMessage = "<red>The config option for this message is missing. Let an admin know!</red>";

        PREFIX = config.getString("pluginPrefix", "<gold>[</gold><green>CritterGuard</green><gold>]</gold>");

        // TOGGLES
        String togglesPath = "toggles.";
        CAN_BREED_LOCKED_ANIMALS = plugin.getConfig().getBoolean(togglesPath + "canBreedLockedAnimals", true);
        LOG_MOUNT_NOTIFICATIONS = plugin.getConfig().getBoolean(togglesPath + "logMountNotifications", true);
        LOG_DISMOUNT_NOTIFICATIONS = plugin.getConfig().getBoolean(togglesPath + "logDismountNotifications", true);
        LOG_DEATH_NOTIFICATIONS = plugin.getConfig().getBoolean(togglesPath + "logDeathNotifications", true);
        ENABLE_DISGUISE_SADDLES = plugin.getConfig().getBoolean(togglesPath + "enableDisguiseSaddles", true);
        ENABLE_MINIMAP_MOD_OUTPUT = config.getBoolean(togglesPath + "enableMinimapModOutput", false);

        // MESSAGES
        // --ACCESS
        String accessPath = "messages.access.";
        GRANTED_FULL_ACCESS = PREFIX
                + " " + config.getString(accessPath + "grantedFullAccess", errorMessage);
        GRANTED_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(accessPath + "grantedPassengerAccess", errorMessage);
        TARGET_GRANTED_FULL_ACCESS = PREFIX
                + " " + config.getString(accessPath + "targetGrantedFullAccess", errorMessage);
        TARGET_GRANTED_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(accessPath + "targetGrantedPassengerAccess", errorMessage);
        REVOKED_FULL_ACCESS = PREFIX
                + " " + config.getString(accessPath + "revokedFullAccess", errorMessage);
        REVOKED_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(accessPath + "revokedPassengerAccess", errorMessage);
        TARGET_REVOKED_FULL_ACCESS = PREFIX
                + " " + config.getString(accessPath + "targetRevokedFullAccess", errorMessage);
        TARGET_REVOKED_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(accessPath + "targetRevokedPassengerAccess", errorMessage);
        ALREADY_HAS_ACCESS = mm.deserialize(PREFIX
                + " " + config.getString(accessPath + "alreadyHasAccess", errorMessage));
        ALREADY_HAS_NO_ACCESS = mm.deserialize(PREFIX
                + " " + config.getString(accessPath + "alreadyHasNoAccess", errorMessage));
        DOES_NOT_SUPPORT_PASSENGERS = mm.deserialize(PREFIX
                + " " + config.getString(accessPath + "entityDoesNotSupportPassengers", errorMessage));
        ACCESS_NO_PLAYER = PREFIX
                + " " + config.getString(accessPath + "unableToFindPlayer", errorMessage);

        // --DISGUISE
        String disguisePath = "messages.disguise.";
        DISGUISE_SUCCESS = PREFIX
                + " " + config.getString(disguisePath + "success", errorMessage);
        DISGUISE_VIEW_SELF_ENABLED = mm.deserialize(PREFIX
                + " " + config.getString(disguisePath + "viewSelfEnabled", errorMessage));
        DISGUISE_VIEW_SELF_DISABLED = mm.deserialize(PREFIX
                + " " + config.getString(disguisePath + "viewSelfDisabled", errorMessage));
        DISGUISE_ALREADY_ENABLED = mm.deserialize(PREFIX
                + " " + config.getString(disguisePath + "alreadyEnabled", errorMessage));
        DISGUISE_ALREADY_DISABLED = mm.deserialize(PREFIX
                + " " + config.getString(disguisePath + "alreadyDisabled", errorMessage));

        // --GPS
        String gpsPath = "messages.gps.";
        GPS_NO_MATCH = PREFIX
                + " " + config.getString(gpsPath + "noMatch", errorMessage);
        GPS_NO_PLAYERMETA = mm.deserialize(PREFIX
                + " " + config.getString(gpsPath + "noPlayerData", errorMessage));

        // --LIST
        String listPath = "messages.list.";
        LIST_DOES_NOT_EXIST_OR_OWN = mm.deserialize(PREFIX
                + " " + config.getString(listPath + "doesntExistOrOwn", errorMessage));
        LIST_NO_MATCH = mm.deserialize(PREFIX
                + " " + config.getString(listPath + "noneMatched", errorMessage));

        // --NOTIFICATION
        String notificationPath = "messages.notification.";
        NOTIFICATION_MOUNTED = PREFIX
                + " " + config.getString(notificationPath + "mounted", errorMessage);
        NOTIFICATION_DISMOUNTED = PREFIX
                + " " + config.getString(notificationPath + "dismounted", errorMessage);
        NOTIFICATION_DIED = PREFIX
                + " " + config.getString(notificationPath + "died", errorMessage);
        NOTIFICATION_TOGGLE_ON = mm.deserialize(PREFIX
                + " " + config.getString(notificationPath + "toggleOn", errorMessage));
        NOTIFICATION_TOGGLE_OFF = mm.deserialize(PREFIX
                + " " + config.getString(notificationPath + "toggleOff", errorMessage));
        NOTIFICATION_ALREADY_ON = mm.deserialize(PREFIX
                + " " + config.getString(notificationPath + "alreadyOn", errorMessage));
        NOTIFICATION_ALREADY_OFF = mm.deserialize(PREFIX
                + " " + config.getString(notificationPath + "alreadyOff", errorMessage));

        // --PERMISSION
        String permissionPath = "messages.permission.";
        PERMISSION_COMMAND = mm.deserialize(PREFIX
                + " " + config.getString(permissionPath + "command", errorMessage));
        PERMISSION_INTERACT = PREFIX
                + " " + config.getString(permissionPath + "interact", errorMessage);
        PERMISSION_MOUNT = PREFIX
                + " " + config.getString(permissionPath + "mount", errorMessage);

        // --SEAT SWAPPING
        String seatSwapPath = "messages.seatSwapping.";
        SEAT_SWAP_SUCCESS = PREFIX
                + " " + config.getString(seatSwapPath + "success", errorMessage);
        SEAT_SWAP_FAILURE = mm.deserialize(PREFIX
                + " " + config.getString(seatSwapPath + "failure", errorMessage));

        // --TAMING
        String tamingPath = "messages.taming.";
        TAMING_TO_THEMSELVES = mm.deserialize(PREFIX
                + " " + config.getString(tamingPath + "tamingToThemselves", errorMessage));
        TAMING_TO_OTHERS = PREFIX
                + " " + config.getString(tamingPath + "tamingToOthers", errorMessage);
        UNTAME = mm.deserialize(PREFIX
                + " " + config.getString(tamingPath + "untame", errorMessage));
        NOT_TAMED = mm.deserialize(PREFIX
                + " " + config.getString(tamingPath + "notTamed", errorMessage));
        TAMED_NOT_YOURS = mm.deserialize(PREFIX
                + " " + config.getString(tamingPath + "notYours", errorMessage));

        // --TELEPORT
        String teleportPath = "messages.teleport.";
        TELEPORT_TO = PREFIX
                + " " + config.getString(teleportPath + "teleportTo", errorMessage);
        TELEPORT_HERE = PREFIX
                + " " + config.getString(teleportPath + "teleportHere", errorMessage);
        TELEPORT_NO_PLAYER = PREFIX
                + " " + config.getString(teleportPath + "unableToFindPlayer", errorMessage);
        TELEPORT_NO_PLAYERMETA = mm.deserialize(PREFIX
                + " " + config.getString(teleportPath + "noPlayerData", errorMessage));
        TELEPORT_NO_MATCH = PREFIX
                + " " + config.getString(teleportPath + "noMatch", errorMessage);

        // --CLICK ACTIONS
        String clickActionsPath = "messages.clickActions.";
        CLICK_GRANT_FULL_ACCESS = PREFIX
                + " " + config.getString(clickActionsPath + "toGrantFullAccess", errorMessage);
        CLICK_GRANT_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(clickActionsPath + "toGrantPassengerAccess", errorMessage);
        CLICK_REVOKE_FULL_ACCESS = PREFIX
                + " " + config.getString(clickActionsPath + "toRevokeFullAccess", errorMessage);
        CLICK_REVOKE_PASSENGER_ACCESS = PREFIX
                + " " + config.getString(clickActionsPath + "toRevokePassengerAccess", errorMessage);
        CLICK_TAME = PREFIX
                + " " + config.getString(clickActionsPath + "toTameToOthers", errorMessage);
        CLICK_UNTAME = PREFIX
                + " " + config.getString(clickActionsPath + "toUntame", errorMessage);
        CLICK_INFO = PREFIX
                + " " + config.getString(clickActionsPath + "toGetInfo", errorMessage);
        CLICK_TIMEOUT = mm.deserialize(PREFIX
                + " " + config.getString(clickActionsPath + "timeout", errorMessage));
    }
}
